name = "newsnow-ppl"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-ppl"
database_id = "59d0b858-7747-459c-9dcf-1748b95b3e2a"
