/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesImport } from './routes/services'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as CoursesImport } from './routes/courses'
import { Route as BlogImport } from './routes/blog'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as CoursesSlugImport } from './routes/courses.$slug'
import { Route as BlogPostIdImport } from './routes/blog.$postId'
import { Route as CoursesSlugLearnLessonIdImport } from './routes/courses.$slug.learn.$lessonId'

// Create/Update Routes

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CoursesRoute = CoursesImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesSlugRoute = CoursesSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)

const BlogPostIdRoute = BlogPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogRoute,
} as any)

const CoursesSlugLearnLessonIdRoute = CoursesSlugLearnLessonIdImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => CoursesSlugRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdImport
      parentRoute: typeof BlogImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugImport
      parentRoute: typeof CoursesImport
    }
    '/courses/$slug/learn/$lessonId': {
      id: '/courses/$slug/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/courses/$slug/learn/$lessonId'
      preLoaderRoute: typeof CoursesSlugLearnLessonIdImport
      parentRoute: typeof CoursesSlugImport
    }
  }
}

// Create and export the route tree

interface BlogRouteChildren {
  BlogPostIdRoute: typeof BlogPostIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogPostIdRoute: BlogPostIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CoursesSlugRouteChildren {
  CoursesSlugLearnLessonIdRoute: typeof CoursesSlugLearnLessonIdRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugLearnLessonIdRoute: CoursesSlugLearnLessonIdRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses/$slug/learn/$lessonId': typeof CoursesSlugLearnLessonIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses/$slug/learn/$lessonId': typeof CoursesSlugLearnLessonIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses/$slug/learn/$lessonId': typeof CoursesSlugLearnLessonIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/login'
    | '/profile'
    | '/services'
    | '/blog/$postId'
    | '/courses/$slug'
    | '/courses/$slug/learn/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/login'
    | '/profile'
    | '/services'
    | '/blog/$postId'
    | '/courses/$slug'
    | '/courses/$slug/learn/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/login'
    | '/profile'
    | '/services'
    | '/blog/$postId'
    | '/courses/$slug'
    | '/courses/$slug/learn/$lessonId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/blog",
        "/courses",
        "/login",
        "/profile",
        "/services"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/blog": {
      "filePath": "blog.tsx",
      "children": [
        "/blog/$postId"
      ]
    },
    "/courses": {
      "filePath": "courses.tsx",
      "children": [
        "/courses/$slug"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/blog/$postId": {
      "filePath": "blog.$postId.tsx",
      "parent": "/blog"
    },
    "/courses/$slug": {
      "filePath": "courses.$slug.tsx",
      "parent": "/courses",
      "children": [
        "/courses/$slug/learn/$lessonId"
      ]
    },
    "/courses/$slug/learn/$lessonId": {
      "filePath": "courses.$slug.learn.$lessonId.tsx",
      "parent": "/courses/$slug"
    }
  }
}
ROUTE_MANIFEST_END */
