/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TemplatesImport } from './routes/templates'
import { Route as CategoriesImport } from './routes/categories'
import { Route as BlogImport } from './routes/blog'
import { Route as IndexImport } from './routes/index'
import { Route as ScenesSceneIdImport } from './routes/scenes.$sceneId'
import { Route as SceneSceneIdImport } from './routes/scene.$sceneId'
import { Route as CategoryCategoryIdImport } from './routes/category.$categoryId'
import { Route as BlogPostIdImport } from './routes/blog.$postId'

// Create/Update Routes

const TemplatesRoute = TemplatesImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesRoute = CategoriesImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ScenesSceneIdRoute = ScenesSceneIdImport.update({
  id: '/scenes/$sceneId',
  path: '/scenes/$sceneId',
  getParentRoute: () => rootRoute,
} as any)

const SceneSceneIdRoute = SceneSceneIdImport.update({
  id: '/scene/$sceneId',
  path: '/scene/$sceneId',
  getParentRoute: () => rootRoute,
} as any)

const CategoryCategoryIdRoute = CategoryCategoryIdImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRoute,
} as any)

const BlogPostIdRoute = BlogPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesImport
      parentRoute: typeof rootRoute
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesImport
      parentRoute: typeof rootRoute
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdImport
      parentRoute: typeof BlogImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdImport
      parentRoute: typeof rootRoute
    }
    '/scene/$sceneId': {
      id: '/scene/$sceneId'
      path: '/scene/$sceneId'
      fullPath: '/scene/$sceneId'
      preLoaderRoute: typeof SceneSceneIdImport
      parentRoute: typeof rootRoute
    }
    '/scenes/$sceneId': {
      id: '/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/scenes/$sceneId'
      preLoaderRoute: typeof ScenesSceneIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface BlogRouteChildren {
  BlogPostIdRoute: typeof BlogPostIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogPostIdRoute: BlogPostIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/templates': typeof TemplatesRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/scene/$sceneId': typeof SceneSceneIdRoute
  '/scenes/$sceneId': typeof ScenesSceneIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/templates': typeof TemplatesRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/scene/$sceneId': typeof SceneSceneIdRoute
  '/scenes/$sceneId': typeof ScenesSceneIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/templates': typeof TemplatesRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/scene/$sceneId': typeof SceneSceneIdRoute
  '/scenes/$sceneId': typeof ScenesSceneIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/categories'
    | '/templates'
    | '/blog/$postId'
    | '/category/$categoryId'
    | '/scene/$sceneId'
    | '/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/categories'
    | '/templates'
    | '/blog/$postId'
    | '/category/$categoryId'
    | '/scene/$sceneId'
    | '/scenes/$sceneId'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/categories'
    | '/templates'
    | '/blog/$postId'
    | '/category/$categoryId'
    | '/scene/$sceneId'
    | '/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  TemplatesRoute: typeof TemplatesRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  SceneSceneIdRoute: typeof SceneSceneIdRoute
  ScenesSceneIdRoute: typeof ScenesSceneIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  TemplatesRoute: TemplatesRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  SceneSceneIdRoute: SceneSceneIdRoute,
  ScenesSceneIdRoute: ScenesSceneIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/categories",
        "/templates",
        "/category/$categoryId",
        "/scene/$sceneId",
        "/scenes/$sceneId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog.tsx",
      "children": [
        "/blog/$postId"
      ]
    },
    "/categories": {
      "filePath": "categories.tsx"
    },
    "/templates": {
      "filePath": "templates.tsx"
    },
    "/blog/$postId": {
      "filePath": "blog.$postId.tsx",
      "parent": "/blog"
    },
    "/category/$categoryId": {
      "filePath": "category.$categoryId.tsx"
    },
    "/scene/$sceneId": {
      "filePath": "scene.$sceneId.tsx"
    },
    "/scenes/$sceneId": {
      "filePath": "scenes.$sceneId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
